/* Published-site knowledge only. This guide does not impersonate Ace or invent answers. */
(function(root){
'use strict';
const records=[
{id:'start',title:'Working session',aliases:['working session','first session','first meeting','try ace','try him','start','book','booking','hire','appointment','consultation','90 minutes','500'],text:'Start with a private working session: CAD $500 for 90 minutes. Bring one meaningful business issue. You receive a focused conversation and a concise, reviewed recap of options and next steps. Send an inquiry first; scope and availability are confirmed before payment.',links:[['Request a working session','contact.html?interest=Working%20session'],['What the session includes','meetings.html']]},
{id:'advisory',title:'Ongoing private advisory',aliases:['advisory','retainer','on call','on-call','ongoing','private advisor','monthly advice','2500','2,500','business help','decision','people','staff','sales','growth','team','problem','strategy'],text:'Ongoing private advisory starts at CAD $2,500 per month. The starting arrangement includes two 60-minute private meetings, up to two additional 30-minute conversations between meetings, and concise decision recaps. It is for owners working through people, sales, growth, and difficult decisions. More involved work is scoped separately.',links:[['Explore private advisory','advisory.html'],['Discuss your situation','contact.html?interest=Ongoing%20advisory']]},
{id:'availability',title:'Access and availability',aliases:['availability','available','response','respond','reply','unlimited','24/7','24 7','emergency','always','anytime','hours','schedule a call','when can'],text:'Meetings and between-meeting calls are scheduled by agreement. Allow up to two business days for a response to your inquiry or scheduling request. Advisory is not emergency or unlimited access. Contact Ace to confirm actual availability; I cannot see his calendar.',links:[['Check availability','contact.html']]},
{id:'price',title:'Fees at a glance',aliases:['price','pricing','cost','fees','how much','budget','charge','rates','expensive','afford','dollars'],text:'All listed fees are in Canadian dollars. A working session is CAD $500 for 90 minutes. Ongoing advisory starts at CAD $2,500/month. Membership tiers are CAD $1,000, $2,000, and $4,000/month. On-site assignments are quoted individually. Scope and any applicable additional costs are confirmed before you commit.',links:[['Working session','meetings.html'],['Advisory','advisory.html'],['Membership tiers','mastermind-membership.html']]},
{id:'currency',title:'Currency',aliases:['currency','usd','cad','canadian dollars','american dollars','us dollars','tax','gst'],text:'Website fees are in CAD, not USD. Confirm applicable taxes and any travel or additional costs in your quote. The transport page specifically states its rates exclude GST.',links:[['Discuss a quote','contact.html']]},
{id:'scope',title:'What is included',aliases:['scope','included','include','execute','execution','implementation','labour','labor','technical','engineering','paperwork','writing','manage staff','deliverables','guarantee','guaranteed','results'],text:'Ace provides conversation, observations, decision preparation, and progress review within an agreed scope. You remain the decision-maker. Staff management, physical labour, routine administration, and specialist technical assessments are outside advisory. Substantial research, travel, and external meetings need a separate agreement. No financial outcome is guaranteed.',links:[['Advisory scope','advisory.html#approach'],['On-site work','scout.html']]},
{id:'scout',title:'On-site assignments',aliases:['scout','scouting','on-site','on site','site visit','property','properties','land','lease','premises','location','travel','investigate','inspection','drone','represent','representation','negotiation'],text:'Ace can investigate agreed locations or premises, document observations, flag practical concerns, and discuss the findings. Price, travel, expenses, and reporting are agreed before work begins. This is observational work, not a licensed survey, appraisal, engineering assessment, or legal or investment advice. Ask Ace directly about meeting representation.',links:[['On-site assignments','scout.html'],['Describe an assignment','contact.html?interest=On-site%20assignment']]},
{id:'about',title:'About Ace',aliases:['who is ace','who is matthew','about ace','about him','about matthew','background','experience','qualifications','credentials','education','career','autodidact','ferguson','construction','film','actor','acting','trades','toastmasters'],text:'Ace is Matthew Ferguson, a Vancouver-based business owner and private advisor. His experience spans sales, skilled trades, business ownership, and years around the film industry. His advisory work has included personnel decisions, business planning, premises searches, and an on-location assignment in Japan. He starts by listening, asking questions, identifying issues, and clarifying next steps.',links:[['Meet Ace','index.html#about'],['His approach','advisory.html#approach']]},
{id:'japan',title:'Japan assignment',aliases:['japan','tokyo','nagano','kyoto','april 2024','yen','forecast','prediction','predicted','proof','case study','case studies','track record','testimonial','testimonials'],text:'In April 2024, Ace undertook a week-long private assignment visiting Tokyo, Nagano, and Kyoto to examine potential locations for a property development opportunity and discuss associated risks. The website describes the work, but does not disclose private client details or claim verified financial savings.',links:[['Read the experience summary','scout.html'],['Client perspective','index.html#about']]},
{id:'membership',title:'Invested Aces membership',aliases:['mastermind','membership','invested aces','join','club','circle','members','network','community'],text:'Invested Aces is a private, application-only circle built around mastermind meetings and shared activities. Membership runs for 12 months, renewable, with monthly or annual payment. The published tiers are CAD $1,000, $2,000, and $4,000 per month. The Lower Mainland is strongly preferred because gatherings are in person.',links:[['Compare member benefits','mastermind-membership.html'],['Apply to Invested Aces','mastermind-application.html']]},
{id:'membership-benefits',title:'Membership benefits',aliases:['member benefits','tiers','tier','1000','1,000','2000','2,000','4000','4,000','benefits','difference','compare'],text:'The CAD $1,000 tier includes one monthly mastermind meeting and group-activity access, with poker RSVP priority. The $2,000 tier adds the second mastermind meeting, up to two one-on-one meetings, and one local transport booking within the stated limits. The $4,000 tier adds up to two on-site business visits and scheduling priority. Read the membership page for exact limits; substantial private projects are agreed separately.',links:[['Full membership terms and benefits','mastermind-membership.html']]},
{id:'mastermind-schedule',title:'Mastermind schedule',aliases:['mastermind dates','mastermind schedule','mastermind when','tuesday','third saturday','second tuesday','where mastermind','private location','meeting dates'],text:'Mastermind meetings are on the second Tuesday and third Saturday of each month. Locations vary and stay private; details are emailed to members two weeks beforehand. Your tier determines access to one or both meetings. Public start times are not listed.',links:[['Mastermind details','mastermind-membership.html']]},
{id:'application',title:'Membership application',aliases:['application','apply','approval','approved','application fee','200','deposit','refund','refundable','stripe','pay membership'],text:'Membership has a CAD $200 application fee covering an initial 60-minute meeting. If approved, it is credited toward the first month’s dues; if not approved, it is non-refundable. The application page uses Stripe. Approval typically takes 2–5 days depending on meeting scheduling, followed by the membership agreement and Community Code of Conduct.',links:[['Membership application','mastermind-application.html'],['Ask before applying','contact.html?interest=Invested%20Aces%20membership']]},
{id:'events',title:'Gatherings',aliases:['events','eventbrite','eventbright','gatherings','activities','calendar','what is on','whats on','next event','social','meet ace','meet him'],text:'Current gatherings include Aces Running Group at Williams Park, a monthly private poker night, and quarterly All Aces Networking. Eventbrite is the source for public event dates, times, prices, and availability. Members request complimentary tickets by email; poker has its own RSVP and buy-in arrangement.',links:[['All gatherings','group-activities.html'],['Running dates & tickets','https://www.eventbrite.ca/e/aces-running-group-tickets-1998266183948'],['Networking tickets','https://www.eventbrite.ca/e/all-aces-networking-event-tickets-1998522196689']]},
{id:'running',title:'Aces Running Group',aliases:['running','run','jog','jogging','williams park','fitness','exercise'],text:'Aces Running Group meets at Williams Park in Langley Township for a social run with peers and professionals, followed by refreshments and conversation. Check the existing Eventbrite listing for selectable dates and current ticket details. Members email Ace for a complimentary ticket.',links:[['Running details','aces-running-group.html'],['Eventbrite dates & tickets','https://www.eventbrite.ca/e/aces-running-group-tickets-1998266183948']]},
{id:'poker',title:'Aces Poker Night',aliases:['poker','cards','buy-in','buy in','100','wednesday','seven seats','7 seats'],text:'Poker night is the third Wednesday of each month at a private location. There are seven open seats, a minimum CAD $100 buy-in, no host cut, and a winner-takes-all format. RSVP by email; mastermind members get first priority. There is no Eventbrite booking link for poker on the site.',links:[['Poker details','aces-poker-night.html'],['Email a poker RSVP','mailto:info@acespaders.com?subject=Aces%20Poker%20Night%20RSVP']]},
{id:'networking',title:'All Aces Networking',aliases:['networking','ricky','rickys','walnut grove','october','oct 23','quarterly','food','coffee','networking time'],text:'All Aces Networking is a quarterly event for business owners at Ricky’s All Day Grill in Walnut Grove. The linked listing is October 23, 2026, noon–6 p.m. Ace opens with a short talk and facilitates conversations. Check Eventbrite for current event and ticket details.',links:[['Networking details','all-aces-networking-events.html'],['Current Eventbrite listing','https://www.eventbrite.ca/e/all-aces-networking-event-tickets-1998522196689']]},
{id:'rsvp',title:'Member event RSVPs',aliases:['rsvp','complimentary','free ticket','member ticket','tickets','non member','non-member','drop in','drop-in'],text:'Non-members use the existing Eventbrite listings for running and networking. Members email info@acespaders.com to request complimentary tickets; those tickets are not public. Poker RSVPs are by email for everyone, with the minimum buy-in still required. Attendance requires a confirmed RSVP.',links:[['Choose a gathering','group-activities.html'],['Email a member RSVP','mailto:info@acespaders.com?subject=Member%20event%20RSVP']]},
{id:'future',title:'Future activities',aliases:['golf','trading club','claude club','vip mixer','future activities','new activities','coming soon'],text:'VIP mixers, the trading club, the Claude Club, and golf gatherings are listed as in development. They are not currently scheduled. The published activity pages distinguish them from the current gatherings.',links:[['Current and future gatherings','group-activities.html']]},
{id:'speaking',title:'Public speaking',aliases:['public speaking','speaker','keynote','talk','speaking','resilience'],text:'Ace considers talks on resilience, personal development, and the practical benefits of networking. Other topics are considered after discussing the audience and brief. Speaking engagements are quoted separately.',links:[['Speaking with Ace','public-speaking.html'],['Discuss a speaking engagement','contact.html']]},
{id:'transport',title:'Premium transport',aliases:['transport','pickup','pick up','truck','cybertruck','airport','ride','delivery','driver','600','1100','175'],text:'Premium pickup and transport in Ace’s Cybertruck is available by arrangement. Published local rates are CAD $200/hour with a three-hour, $600 minimum, or a six-hour $1,100 package. Member rates are CAD $175/hour, with some tiers including a limited booking. Rates exclude GST; itinerary, availability, deposits, and terms are confirmed separately.',links:[['Transport details','premium-pickup-transport.html'],['Request a transport quote','contact.html']]},
{id:'contact',title:'Contact Ace',aliases:['contact','email','telephone','phone number','address','where is ace','vancouver','canada','location of ace','reach ace','message ace'],text:'Email info@acespaders.com or use the inquiry page to prepare an email. Ace is based in Vancouver, British Columbia, and meetings are by appointment. Allow up to two business days for a reply. I cannot book, take payment, or send a message on your behalf.',links:[['Prepare an inquiry','contact.html'],['Email Ace','mailto:info@acespaders.com']]},
{id:'mlb',title:'Make Life Better',aliases:['make life better','mlb','trade show','other business','president','ceo'],text:'Make Life Better is Ace’s separate business and events brand. This website focuses on his private advisory and Invested Aces. Visit MakeLifeBetter.today for information about that business.',links:[['Make Life Better','https://www.makelifebetter.today']]},
{id:'personal',title:'A business owner’s perspective',aliases:['personal','health','mindset','stress','motivation','habits','gym','coaching','life coach'],text:'Ace’s conversations can include perspective, motivation, and the pressures an owner is navigating. The main service here is business advisory. It is not medical care, therapy, or a personal training programme. Ask Ace directly whether your situation fits.',links:[['Meet Ace','index.html#about'],['Discuss your situation','contact.html']]},
{id:'privacy',title:'About this chat',aliases:['privacy','private','data','save chat','saved','record','ai','chatbot','bot','are you ace','who are you','human','little ace'],text:'I’m Little Ace, an automated site guide—not Matthew himself. I match questions to a curated set of published site answers and links. This chat runs in your browser; messages are not sent to Ace or an AI service and are not saved between page loads. For personal advice or anything not covered here, contact Ace.',links:[['Contact the real Ace','contact.html']]},
{id:'us',title:'Travel and location',aliases:['america','american','united states','usa','citizenship','visa','immigration','move','relocate'],text:'Ace is currently based in Vancouver, BC. On-site travel is considered as part of an agreed assignment. This site does not offer immigration advice or promise U.S. availability; ask Ace about a specific location and itinerary.',links:[['Discuss an assignment','scout.html']]}
];
const normalize=s=>s.toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9$]+/g,' ').trim();
const stop=new Set('a an the is are was were be been can could would should do does did i me my you your he his him it its they them their this that about what how why where when who which to for of on in with and or as at tell please want need know more some much any have has will get'.split(' '));
function tokens(s){return normalize(s).split(' ').filter(t=>t.length>1&&!stop.has(t));}
function answer(query,last){
 const q=normalize(query);if(!q)return null;
 if(/^(hi|hello|hey|hello ace|hi ace|hey ace|good morning|good evening)$/.test(q))return {id:'greeting',title:'Hello',text:'Hi, I’m Little Ace. I can help you explore private advisory, learn about Matthew, or find the right gathering. What would you like to know?',links:[]};
 if(/^(thanks|thank you|cheers|great|ok|okay)$/.test(q))return {id:'thanks',title:'You’re welcome',text:'You’re welcome. If you want to speak with Matthew about your own situation, the inquiry page is the next step.',links:[['Work with Ace','contact.html']]};
 if(q.includes('ignore previous')||q.includes('system prompt')||q.includes('api key'))return {id:'fallback',title:'Site questions',text:'I can help with Ace’s published services, background, and events. What would you like to explore?',links:[]};
 let augmented=query;
 const followup=/^(and |what about |how much|what does it cost|where is it|when is it|how do i join|how do i book|tell me more|what is included)/.test(q);
 if(followup&&last&&last!=='price'&&last!=='events'){
  const previous=records.find(r=>r.id===last);
  if(previous&&['running','poker','networking','membership','advisory','start','transport','scout'].includes(last)){
   if(/how much|cost|price|included|tell me more|where|when/.test(q))return {...previous};
  }
 }
 let best=null,score=0,qt=tokens(augmented);
 for(const record of records){let n=0;
  for(const alias of record.aliases){const a=normalize(alias);if((' '+q+' ').includes(' '+a+' ')){n+=a.includes(' ')?7+Math.min(a.length/8,4):3;}}
  const doc=new Set(tokens(record.title+' '+record.aliases.join(' ')));
  for(const t of qt)if(doc.has(t))n+=1.4;
  if(q.includes('mastermind')&&record.id==='mastermind-schedule'&&/when|where|date|time|schedule/.test(q))n+=18;
  if(/membership|mastermind/.test(q)&&/price|cost|how much/.test(q)&&record.id==='membership')n+=16;
  if(/advisory|retainer/.test(q)&&record.id==='advisory')n+=16;
  if(/are you.*ace|are you.*human|are you.*ai|are you.*bot/.test(q)&&record.id==='privacy')n+=25;
  if(n>score){score=n;best=record;}
 }
 if(score<3)return {id:'fallback',title:'Ask Ace directly',text:'I don’t have a reliable published answer to that. I can explain Ace’s services, fees, background, and events—or point you to him for a personal answer.',links:[['Ask Ace','contact.html'],['Explore advisory','advisory.html']]};
 return {...best};
}
const api={records,answer};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.AceKnowledge=api;
})(typeof window!=='undefined'?window:globalThis);
